### ISSUE TITLE
Add ability to download logs from FC

### ISSUE THREAD

**Issue by mituritsyn** [betaflight/blackbox-log-viewer#570] opened 2022-04-16 10:40 UTC
### Is your feature request related to a problem? Please describe

You always need to open BF Configurator first

### Describe the solution you'd like

Port from BF Configurator "activate mass storage device mode" and "save to file" options so one doesn't need to open configurator first to get log files

### Describe alternatives you've considered

-//-

**Comment by mituritsyn** [comment] 2022-05-17 05:55
still here

**Comment by haslinghuis** [comment] 2024-05-29 21:02
Closing for now. This will be possible when we integrate both clients into one app by design.

**Closed by haslinghuis** 2024-05-29 21:02 UTC
Labels: feature request
