### ISSUE TITLE
Blackbox Explorer 3.3 shows incorrect gyro traces

### ISSUE THREAD

**Issue by MikeWhy** [betaflight/blackbox-log-viewer#318] opened 2019-04-18 14:27 UTC
On updating Blackbox Explorer to 3.3 from 3.2, the displayed Gyro traces are all saturated at full scale, and not readable. The Gyro traces display correctly (or, just reasonably) in BB Explorer 3.2.

**Comment by mikeller** [comment] 2019-04-29 11:34
Duplicate of #307.

**Closed by mikeller** 2019-04-29 11:34 UTC
